name: onah_portfolio
description: "Online Portfolio for csonah"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.3
  firebase_core: ^3.3.0
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  animated_text_kit: ^4.2.3
  url_launcher: ^6.3.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  android: "launcher_icon" # flutter pub run flutter_launcher_icons
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png" # edit paths
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#000000"
    theme_color: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Michroma
      fonts:
        - asset: assets/fonts/Michroma-Regular.ttf
    - family: CormorantInfant
      fonts:
        - asset: assets/fonts/CormorantInfant-Bold.ttf
          weight: 700
        - asset: assets/fonts/CormorantInfant-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/CormorantInfant-Medium.ttf
          weight: 500
        - asset: assets/fonts/CormorantInfant-Regular.ttf
          weight: 300
        - asset: assets/fonts/CormorantInfant-Light.ttf
          weight: 200
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Regular.otf
          weight: 400