name: onah_portfolio
description: "Online Portfolio for csonah"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.3
  firebase_core: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images
    - assets/svgs

  fonts:
    - family: Michroma
      fonts:
        - asset: assets/fonts/Michroma-Regular.ttf
    - family: CormorantInfant
      fonts:
        - asset: assets/fonts/CormorantInfant-Bold.otf
          weight: 700
        - asset: assets/fonts/CormorantInfant-SemiBold.otf
          weight: 600
        - asset: assets/fonts/CormorantInfant-Medium.otf
          weight: 500
        - asset: assets/fonts/CormorantInfant-Regular.otf
          weight: 300
        - asset: assets/fonts/CormorantInfant-Light.otf
          weight: 200