// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5fXjYkjGrkgpWMb0ZUSxw9dfc4G8iGrc',
    appId: '1:765986511047:web:903f295a0a4a535a5f46e2',
    messagingSenderId: '765986511047',
    projectId: 'onah-s-portfolio',
    authDomain: 'onah-s-portfolio.firebaseapp.com',
    storageBucket: 'onah-s-portfolio.appspot.com',
    measurementId: 'G-B0350SSQSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTuwe0oqQ4IcXeN3D7UZn2k7IOapEycIE',
    appId: '1:765986511047:android:d9f4174d65fe741d5f46e2',
    messagingSenderId: '765986511047',
    projectId: 'onah-s-portfolio',
    storageBucket: 'onah-s-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKrFQ92smnhgZIIIyKsixRdmA_St_Bt7w',
    appId: '1:765986511047:ios:06dbeab4863edb7c5f46e2',
    messagingSenderId: '765986511047',
    projectId: 'onah-s-portfolio',
    storageBucket: 'onah-s-portfolio.appspot.com',
    iosBundleId: 'com.csonah.onahPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKrFQ92smnhgZIIIyKsixRdmA_St_Bt7w',
    appId: '1:765986511047:ios:06dbeab4863edb7c5f46e2',
    messagingSenderId: '765986511047',
    projectId: 'onah-s-portfolio',
    storageBucket: 'onah-s-portfolio.appspot.com',
    iosBundleId: 'com.csonah.onahPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5fXjYkjGrkgpWMb0ZUSxw9dfc4G8iGrc',
    appId: '1:765986511047:web:f74fa8dc7120d0f35f46e2',
    messagingSenderId: '765986511047',
    projectId: 'onah-s-portfolio',
    authDomain: 'onah-s-portfolio.firebaseapp.com',
    storageBucket: 'onah-s-portfolio.appspot.com',
    measurementId: 'G-ETL82NT93P',
  );
}
